### ISSUE TITLE
Using backslash in destinationRootDirectory leads to strange behavior

### ISSUE THREAD

**Issue by abeggchr** [scenarioo/scenarioo-cs#10]
Using a backslash in the destinationRootDirectory argument of the ScenarioDocuWriter led to a strange behavior (uncaught exception or something). Adding a second constructor taking a FileInfo as destinationRootDirectory would be great.

Wrong:

```
var scenarioDocuWriter = new ScenarioDocuWriter("E:\Scenarioo\", branch, build);
```

Correct:

```
var scenarioDocuWriter = new ScenarioDocuWriter("E:/Scenarioo/", branch, build);
```

Better:

```
var scenarioDocuWriter = new ScenarioDocuWriter(new FileInfo("E:/Scenarioo/"), branch, build);
```

**Comment by tobiaszuercher** [comment]
hi @abeggchr 
sorry because of too many github notifications i didn't see this one.

your wrong code is even more wrong than you think: your \ needs to be escaped.

fix with @:
`var scenarioDocuWriter = new ScenarioDocuWriter(@"E:\Scenarioo", branch, build);`

or like in other languages normal escaping:
`var scenarioDocuWriter = new ScenarioDocuWriter("E:\\Scenarioo", branch, build);`

in my eyes this isn't a bug.
