### ISSUE TITLE
Disallow slashes in C# API

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo-cs#9]
As a solution for issue #287 slashes and backslashes are disallowed in the C# API.

(this issue was moved here from the Scenarioo Viewer repository, see scenarioo/scenarioo#325)

**Comment by bruderol** [comment]
hmm, this is really a breaking change (as @tobiaszuercher mentioned correctly).
Didn't we once define to sanitize it and bring up a warning instead of blocking? what does the Java library do?

In general, I do not like, that the writer does not accept all characters, because it makes writing the integration into tests more difficult, because the developer might have to implement this extra checks and transformation of names. I think that the writer library should help in this cases and provide an automatic workaround (=sanitizing the names automatically and bring a warning and not throw an exception).

**Comment by adiherzog** [comment]
Here's the solution that we aggreed on: https://github.com/scenarioo/scenarioo/issues/287

**Comment by bruderol** [comment]
@adiherzog Hum - please define "aggreed on" :wink: :smile:
I would say, that I was kind of overruled, and I never agreed in the discussion on the issue to forbid this characters by failing with an exception, instead of just warn the user.
But ok, you are right, it was then decided to forbid it in version 2.0 in the Java library (which was never implemented in the C# library, because not important).

I still think, that a writer library should accept as much content as possible (and sanitize it automatically where needed, with a warning), especially for names (because names of Scenarioo objects might come from sources that can contain all kind of characters and the developer should not have to care about this, either the library, or even better the server, should care about this). And since the server accepts slashes (and sanitizes them, even if this sanitizing is maybe not optimal, because not unique), I do still think, that the library should continue to allow them (and maybe just throw a warning, if realy important). Also we might have to reconsider to improve the sanitizing of slashes (maybe just replace it in links in URLs with some special code??, because that is the place where those characters really cause troubles).

**Comment by bruderol** [comment]
**important side note:** if this issue is going to be implemented it would be important to warn all C# projects from updating. I know at least of one project that probably still writes Scenarioo objects with slashes in their names (without ever having big troubles with this, at least they never complained)
**--> which is another argument to discard this issue and not implement it!**

**Comment by adiherzog** [comment]
I don't mind if the C# solution is not the same as the Java API, so just replacing all slashes by an underscore and writing a warn log statement would be ok as well, I guess.

Probably it's better to do the sanitizing in the writer library so that the API user can see the warnings immediately. Or alternatively we could implement the "warnings / errors / infos" concept when a build is imported in the viewer and put it there. But then the roundtrip time would be a bit longer to discover such issues.

**Comment by tobiaszuercher** [comment]
so what is the decision now?

**Comment by bruderol** [comment]
the decission is:
We have to reconsider this topic and discuss another overal solution that is more usable and causes less troubles.
I think for now, we should not implement anything concerning this (at least in C# library), which means to allow everything, until we have decided about this topic.

Adrian and me discussed today and we found a possible solution that is more server-centric:
I describe it in a separate issue ... coming soon ... i will link here.

**Comment by bruderol** [comment]
Ok ... here it comes ... I rethought about it and have now a more precise answer with some options:

My thoughts, reconsidering all the discussions:
1. This is not high prio (or is there any project having trouble with this?), as soon as there is, we should fix it.
2. Therefore we can for now ignore it, as a "known issue" ---> means that nobody is implicitly allowed to use slashes or backslashes in name fields (except for page names, where some projects are using it currently, and the server is therefore allowing and sanitizing it!).
3. If we currently implement anything in writer libraries about this, we should go for the following, backwards compatible solution: sanitize names in writer libraries, such that nobody have troubles with this characters and put a warning into the log file (since also @adiherzog agreed above, that this would be okay for now).
4. later (in version 3), we should go for following proposed solution: scenarioo/scenarioo#450 (please discuss there!)

That's it. Can we all live with that descission?

@tobiaszuercher you can decide whether you want to do something about it (3.) or ignore it (2. because of 1.) for now, meaning only to solve it in version 3 (4.) when we implement the new format.

**Comment by tobiaszuercher** [comment]
nobody complained about it so we will have a nice solution for it in the new format!
